language: php

php:
  - 5.6
  - 7

install: composer install --optimize-autoloader --no-suggest --no-interaction --prefer-source

script:
  - bin/phpunit
  - bin/phpmd src html cleancode,codesize,controversial,design,naming,unusedcode
  - bin/phpcs
