app:
  build: .
  ports:
    - "9000:9000"
  links:
    - elasticsearch:elasticsearch

elasticsearch:
  image: elasticsearch:5.1.2
  ports:
    - "9200:9200"
    - "9300:9300"

kibana:
  image: kibana:5.1.2
  ports:
    - "5601:5601"
  links:
    - elasticsearch:elasticsearch
